### ISSUE TITLE
movingAvg.h

### ISSUE THREAD

**Issue by paulw517** [JChristensen/movingAvg#8]
Jack, i am attempting to implement your movingAvg.h library to calculate the average receive an message timing between a pair of RN2903 LoRa radios and ESP32 DEV Modules with Arduino IDE ver. 1.8.12 to improve reception timing.  However, I received the following message after compiling my sketch after including your #include <movingAvg.h> library:

WARNING: library movingAvg claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).

What do you suggest,

Paul D. Wilkie
Do_Not_Give_Up

**Comment by JChristensen** [comment]
Hello Paul,

Try changing the [architectures line in the library.properties file](https://github.com/JChristensen/movingAvg/blob/976ad074ab811a56f4b3f4519c32aafb07e72acb/library.properties#L9) to read as follows:
```c++
architectures=*
```
(I only work with the AVR architecture. Since I am unable to test or debug on other architectures, I prefer not to advertise my libraries as such.)

Cheers
